name: help_me
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  circular_chart_flutter: ^0.0.2
  cloud_firestore: ^4.17.3
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.3
  firebase_auth: ^4.19.5
  firebase_core: ^2.32.0
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_facebook_auth: ^7.0.0
  flutter_riverpod: ^1.0.3
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  timeago: ^3.6.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - public/assets/images/biceps.jpg
    - public/assets/images/back.jpg
    - public/assets/images/chest.jpg
    - public/assets/images/shoulder.jpg
    - public/assets/images/squats.jpg
    - public/assets/images/fullBody.jpg
    - public/assets/images/gym.jpg
    - public/assets/images/dumbell.jpg
    - public/assets/images/protein.jpg
    - public/assets/images/carbs.jpg
    - public/assets/images/fat.jpg
    - public/assets/images/fiber.jpg
    - public/assets/images/calcium.jpg
    - public/assets/images/iron.jpg
    - public/assets/images/magnesium.jpg
    - public/assets/images/vitamins.jpg
    - public/assets/images/zinc.jpg
    - public/assets/images/logo.jpg
    - public/assets/images/foodAddIcon.jpg
    - public/assets/images/splashScreenExercise.jpg
    - public/assets/images/googleLogo.jpg
    - public/assets/images/facebookLogo.jpg
    - public/assets/images/twitter.jpg
