// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtQorWbxnmUHd3NJYdvWmGlnbpY1a5S08',
    appId: '1:1004511462404:web:619125a0a6fb081b83e151',
    messagingSenderId: '1004511462404',
    projectId: 'appdev-ce776',
    authDomain: 'appdev-ce776.firebaseapp.com',
    databaseURL: 'https://appdev-ce776-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appdev-ce776.appspot.com',
    measurementId: 'G-8LCRCLSHKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChnY8FF-AzZGfbzir2gXVEg2S-S4xD00g',
    appId: '1:1004511462404:android:de97329045e0a55b83e151',
    messagingSenderId: '1004511462404',
    projectId: 'appdev-ce776',
    databaseURL: 'https://appdev-ce776-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appdev-ce776.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVB-pW23F9OQVw1FDtQJBPQbT28hyqaIs',
    appId: '1:1004511462404:ios:c027dea51d47af7283e151',
    messagingSenderId: '1004511462404',
    projectId: 'appdev-ce776',
    databaseURL: 'https://appdev-ce776-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appdev-ce776.appspot.com',
    androidClientId: '1004511462404-ddrau4ff092lakde2rehgmi0pvvoj3f1.apps.googleusercontent.com',
    iosClientId: '1004511462404-3cdn2ddjg06enqe5muph2q5jn60gp1b3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitXperience',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVB-pW23F9OQVw1FDtQJBPQbT28hyqaIs',
    appId: '1:1004511462404:ios:c027dea51d47af7283e151',
    messagingSenderId: '1004511462404',
    projectId: 'appdev-ce776',
    databaseURL: 'https://appdev-ce776-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appdev-ce776.appspot.com',
    androidClientId: '1004511462404-ddrau4ff092lakde2rehgmi0pvvoj3f1.apps.googleusercontent.com',
    iosClientId: '1004511462404-3cdn2ddjg06enqe5muph2q5jn60gp1b3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitXperience',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtQorWbxnmUHd3NJYdvWmGlnbpY1a5S08',
    appId: '1:1004511462404:web:5619d98d521d870383e151',
    messagingSenderId: '1004511462404',
    projectId: 'appdev-ce776',
    authDomain: 'appdev-ce776.firebaseapp.com',
    databaseURL: 'https://appdev-ce776-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appdev-ce776.appspot.com',
    measurementId: 'G-BS3DQMWKQF',
  );

}